



[section]

[Header
  title:"The Shortest Splitline Algorithm"
  subtitle:"Gerrymandering and Political Districting"
  author:"Devin Garg, Sofie Blankenship, Ryan Fok, Quan The Tran" /]

The [link text:"shortest splitline algorithm" href:"http://www.rangevoting.org/GerryExamples.html" /] is a simple mechanical procedure that can be used for drawing lines to form political districts, based solely on population. Currently, political districts in the United States are drawn through gerrymandering, which is a practice intended to establish an advantage for a certain political party or group. By using the shortest splitline algorithm, political districts can be drawn based on the population of certain regions, thus eliminating the bias of gerrymandering. Though in some cases, this may not eliminate political advantages, it nevertheless is an unbiased method of political districting that would elicit less controversy.

Gerrymandering tends to result in odd, skinny, and sprawling districts that pack minority voters into as few districts as possible. This can lead to self-reinforced [link text:"single party domination" href:"http://www.rangevoting.org/OneParty.html" /] within a state. As an example, North Carolina has a historically high rate of gerrymandering. In the image below are the party results of the 2014 congressional elections in each Republican-drawn district.

[img width:"500" src:"https://cdn-images-1.medium.com/max/1600/1*sxF6Gjkpm7Ajk17i73iiNw.png" /]

As you can see, district 1 is very broad and spread out across the northern part of the state, with many small outlets branching out of it. Additionally, district 12 is long and skinny, stretching between a few urban areas in the midwestern part of the state. North Carolina's strategy for drawing districts has been to pack minority voters into districts 1 and 12, which has heavily affected the outcome of elections. More recently, the [link text:"Supreme Court rejected these two gerrymandered districts" href:"https://www.nytimes.com/2017/05/22/us/politics/supreme-court-north-carolina-congressional-districts.html" /], ruling that lawmakers factored in race in drawing them.

Even with supposedly [link text:"independent or bi-partisan commissions" href:"http://www.rangevoting.org/GerryComm.html" /], gerrymandering is still a problem. For example, consider the Washington state's congressional districts from 2012, which has a five-member independent district-drawing commission.

[img width:"500" margin:"auto" src:"https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/United_States_Congressional_Districts_in_Washington%2C_2003_%E2%80%93_2013.tif/lossless-page1-1024px-United_States_Congressional_Districts_in_Washington%2C_2003_%E2%80%93_2013.tif.png" /]

Here, you can see that districts 1 and 7 start on land and stretch across the Puget Sound to even more land.

Read further to learn about how the algorithm works. Afterwards, you can see what North Carolina's and Washington's congressional district map would look like with the shortest splitline algorithm.

# How the Algorithm Works

The algorithm takes as input the shape of a country/state/region, the locations of its inhabitants, and a positive number *dists* representing desired number of districts. It then divides that country/state/region into *dists* equipopulous districts.

## Step 1: Choose inputs
We first have to decide how many districts we want to divide the state/region into, and the population for the district. The number of districts, *dists*, that we decide on will divide the state into *dists* districts such that each district has the same population as every other district.

```
shortestSplitline (region, dists) {
```

## Step 2: Split the region into two districts, or return the entire district
If *dists* = 1, we output the entire region as the district.

```
If N = 1 then output entire state as the district;
```

Otherwise, we find the shortest line that splits the region into two equipopulous districts and draw it.

This is done by first separating the current number of districts into two, nearly equal whole numbers A and B, where *dists* = A + B. If *dists* is even, then we would have A = B. For example, we would separate *dists* = 8 into A = 4 and B = 4 since 8 = 4 + 4. If *dists* is odd, then we would have A = B + 1. For example, we would separate *dists* = 7 into A = 4 and B = 3 since 7 = 4 + 3.

```
a = floor (dists / 2);
b = ceiling (dists / 2);
```

After doing this, we find the shortest splitline that gives us an A:B population ratio. This is done with the following criteria in mind:

1) If there is an exact length tie for shortest line, then use the line closest to a North-South orientation. If still a tie, use the westernmost dividing line.

2) If the region is nonconvex, a line could split it into more than two pieces, which, though rare, could still occur. As an example, consider a NW-SE splitline on Florida:

[img width:"300" layout:centered src:"images/nonconvex.jpg" /]

The algorithm disregards this case so that the length of the splitline, regardless of the shape of the region, is equal to the distance between the two furthest points of the line that both lie WITHIN the region being split. In the example above, then, the region being split is the entire state of Florida, and the splitline would run from point A to point B, which both lie within the region being split.

3) If someone's residence is split in two by a splitline, then they are declared to lie in the westernmost, or northernmost if line is EW, of the two districts.

```
find the shortest splitline with a:b population ratio;
```

Drawing the line will split the region into two hemi-states with an A to B population ratio: region A will have A districts and region B will have B districts.

```
draw the splitline and split region into regionA and regionB
```

## Step 3: Recursively split districts into smaller districts
If more districts are desired, we recurse by repeating step 2, using the subdistrict to find another shortest splitline that will further split it into two equipopulous districts.

This means we call the algorithm with regionA and regionB, where the number of districts in each region is, respectively, A and B.

```
shortestSplitline (regionA, a);
shortestSplitline (regionB, b);
```

Putting it all together, the complete pseudocode for the [link text:"formal recursive algorithm" href:"http://www.rangevoting.org/SSArecursive.txt" /] is:

```
shortestSplitline (region, dists) {
  if dists = 1 then output the region as the district;
  a = floor (dists / 2);
  b = ceiling (dists / 2);
  find the shortest splitline with a:b population ratio, breaking ties 
  by the following criteria:
    if exact-length tie, then use the line closest to North-South
    orientation, and if still a tie, use Westernmost line.
  draw the splitline and split region into regionA and regionB;
  shortestSplitline (regionA, a);
  shortestSplitline (regionB, b);
```

# Advantages and Disadvantages
The advantage of using the shortest splitline algorithm for drawing congressional districts is that there is one and only one possible drawing given number of districts, state, and distribution of population. This does not account for race, ethnicity, political affiliation, or any such demographics, meaning that the districting will be completely unbiased.

In addition, the algorithm generally results in simple-shaped districts. This makes it easier to figure out what district you live in, especially considering that gerrymandered districts can be thin and sprawling. All of this means that using this algorithm for political districting would make the elections process more fair and convenient for voters.

Nonetheless, the disadvantage to the algorithm is that it ignores geographic features (ex: rivers and highways) as well as political features (ex: county boundaries). Sometimes, politicians will use such features to deny people fair representation, as in this example of congressional districts in Chicago, Illinois.

[img width:"500" src:"http://www.rangevoting.org/ChicagoCloseup.gif" /]

Many of these districts have small outcroppings, such as in district 1 and 10. However, look closely at district 4, which wraps westwards and around district 7 to another broad region. The thin strip actually lies entirely inside a highway, connecting the two larger regions that comprise district 4.

# Conclusion
The shortest splitline algorithm can be used for unbiased political districting, as a replacement for the practice of gerrymandering. Rather than purposely giving one political party of group an advantage, the algorithm disregards party affiliations by splitting regions based on population. There are some disadvantages to the algorithm, namely that it ignores geographic and political features, but these disadvantages are small in comparison to having a less corrupt, more democratic government that allows for fair representation.

## References

[link text:"The website we referenced for information on the algorithm and the pseudocode" href:"http://www.rangevoting.org/GerryExamples.html" /].

[link text:"A short video that briefly describes the algorithm" href:"https://l.messenger.com/l.php?u=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DkUS9uvYyn3A&h=ATO3wgSm5BhKXAowOzVL7wOulvkREiIk4ewVKSwLeSsAxUbzdSeOSmThoqgZADk1AO0voDqwH_C4X-6mLc-fnskwab2O-G6sdt-bhzlMOGQ5RbAK3wY7TSv0NI_tSUpe5phIa3DuwO-r&s=1&enc=AZMsXtZ0o4qkKDmcIUj3xF4p7Zwk1VWyni5Ks49AEZvLfmrKxlaYMz32jn21J92tJ3nMr1jg5Myl_5OprYqYbvsYonna9laf4mMRaOzocTDhRA" /].

[/section]

[fixed]

[Inline] 



[var name:"stateName" statesnamenew:"Washington" /]
[var name:"mySliderVal" value:10 /]
[var name:"myMin" value:6 /]
[var name:"myMax" value:14 /]
[var name:"myStep" value:4 /]
[var name:"myStackTraceVal" value:10 /]
[var name:"myStackTraceMax" value:10 /]

Choose what state to visualize: 
[MyDropdown statesnamenew:stateName min:myMin max:myMax step:myStep def:mySliderVal changingMyStack:myStackTraceVal maxMyStack:myStackTraceMax/]
[CustomD3Component statesnamenew:stateName sliderWhich:mySliderVal stackLookingInto:myStackTraceVal/]

Number of Districts: 
[Display value:mySliderVal /]

[Range value:mySliderVal min:myMin max:myMax step:myStep myState:stateName changingStack:myStackTraceVal maxStack:myStackTraceMax /]
[br/]
Split Lines in Order of Running Splitting Algorithm:  
[CustomDisplay value:myStackTraceVal myCustomDisplayMax:myStackTraceMax/]

[StackTrace value:myStackTraceVal min:1 max:myStackTraceMax step:1 /]




[/Inline]

[/fixed]
